Course.create(name: "Elixir", description: "Learn Functional Programming")
Course.create(name: "Taking a walk and thinking about stuff", description: "See name")
Course.create(name: "Code Mixing", description: "Hip-Hop & Programming 101")
Course.create(name: "social skills", description: "i have no social skills")
Course.create(name: "Cocktails 101", description: "teach us nice drinks plz")
Course.create(name: "Fred", description: "best weekend ever")
Course.create(name: "Node", description: "Learn Node")
Course.create(name: "Silly Walking with pants", description: "silly walking.")
Course.create(name: "Dragon Wrangling", description: "Wrangle dragons")
Course.create(name: "ninja rabbits", description:"what it sounds like")
Course.create(name: "Climbing", description: "Win over your fear of heights")
Course.create(name: "Scuba Diving", description: "Get your scuba on")
Course.create(name: "sword making", description: "make swords")
Course.create(name:"Talk...ing", description: "Witty raconteuring 101")
Course.create(name: "Digital Marketing", description: "Dolla bills")
Course.create(name: "Transmogrification", description: "make something out of something else")
Course.create(name: "Cat petting", description: "Pet them cats")
Course.create(name: "Cheese Tasting", description: "Eat lots of cheese")
Course.create(name: "bartending", description: "alcohol")
Course.create(name: "freerunning", description: "run")
Course.create(name: "Water Bending", description: "Make M. Night Shyamalan weep on command")
Course.create(name:"Geordie", description:"Way aye man")
Course.create(name:'vim',description:'but why would anyone want to--')
Course.create(name: "sponge", description: "squeak")
